#!/usr/bin/env python3
"""Generates a Cloudflare Pages _headers file that applies the COOP/COEP
headers the coding-window tool's interactive stdin needs, scoped ONLY to
pages that actually embed the tool.

Why not a blanket "/*" rule: cross-origin isolation (COEP) blocks any
cross-origin subresource that doesn't send a matching
Cross-Origin-Resource-Policy header. YouTube video embeds and Google Docs
embeds both lack that header (confirmed), so a blanket rule silently breaks
them anywhere they appear in the book. Scoping to only the pages that need
isolation means nothing else - including embed types not yet audited - is
ever at risk.

Why generate this instead of hand-maintaining a list: the set of pages that
embed the coding-window tool changes as the book's content changes. Deriving
it fresh from the actual build output every deploy means this can never
drift out of sync with what's really in the book.

Cloudflare Pages automatically 308-redirects "/page.html" to the
extension-less "/page" as the canonical URL (confirmed live) - so the rule
path must be the extension-less form, not the ".html" filename. Getting
this wrong doesn't error or warn anywhere; it just silently no-ops, since
the header ends up on the invisible redirect hop instead of the page the
browser actually renders. Confirmed this the hard way once already -
tested only the redirect hop's headers, not the final destination's, and
mistakenly reported the fix as verified when the real page had no headers
at all.

Usage: python3 generate-headers.py <built-site-dir> <output-headers-path>
"""
import sys
from pathlib import Path

NEEDLE = "coding-window/index.html"

HEADER_COMMENT = """# Isolation headers ONLY for pages that embed the client-side coding-window
# tool's interactive stdin - see coding-window/README.md. Generated by
# generate-headers.py from the actual build output - do not hand-edit or
# commit a static copy, it will drift out of sync with the book's content.
# Deliberately an allow-list, not a blanket /* with exceptions: cross-origin
# embeds elsewhere in the book (YouTube videos, Google Docs, and potentially
# others) send no Cross-Origin-Resource-Policy header, so COEP would silently
# break any of them on any page that got it by default.
"""


def main():
    if len(sys.argv) != 3:
        print("Usage: python3 generate-headers.py <built-site-dir> <output-headers-path>", file=sys.stderr)
        sys.exit(1)

    site_dir = Path(sys.argv[1])
    output_path = Path(sys.argv[2])

    pages = []
    for html_file in sorted(site_dir.glob("*.html")):
        if NEEDLE in html_file.read_text(errors="ignore"):
            pages.append(html_file.name)

    lines = [HEADER_COMMENT]
    # Cross-origin isolation must propagate through every frame in the
    # ancestor chain (empirically confirmed earlier), so the coding-window
    # tool's own files need these headers too, on top of whichever parent
    # page embeds it. Safe to always isolate this path regardless of which
    # page loaded it: only allow-listed pages ever embed it in the first
    # place.
    lines.append("/coding-window/*")
    lines.append("  Cross-Origin-Opener-Policy: same-origin")
    lines.append("  Cross-Origin-Embedder-Policy: require-corp")
    lines.append("")
    for page in pages:
        # Strip .html: Cloudflare serves the extension-less URL as canonical
        # and redirects the .html one there, so the rule has to target what
        # the browser actually ends up on, not the requested filename.
        clean_path = page[:-len(".html")] if page.endswith(".html") else page
        lines.append(f"/{clean_path}")
        lines.append("  Cross-Origin-Opener-Policy: same-origin")
        lines.append("  Cross-Origin-Embedder-Policy: require-corp")
        lines.append("")

    output_path.write_text("\n".join(lines))
    print(f"Generated {output_path} with isolation headers for {len(pages)} pages plus /coding-window/*.")


if __name__ == "__main__":
    main()
