#!/usr/bin/env python3
"""Generates a Cloudflare Pages Function (functions/_middleware.js) that
applies the COOP/COEP headers the coding-window tool's interactive stdin
needs, scoped ONLY to pages that actually embed the tool.

Supersedes generate-headers.py's static _headers file, which hit a hard
wall: Cloudflare Pages caps a _headers file at 100 header rules (documented:
https://developers.cloudflare.com/pages/configuration/headers/#limits). This
book now needs isolation on more pages than that (118 as of this writing),
and pages sorted past the cutoff silently lost their headers with no error
or warning anywhere - confirmed live, this is exactly what broke interactive
stdin on the Strings chapter while earlier-sorting chapters kept working. A
Pages Function is real per-request code (a Cloudflare Worker under the
hood), not a size-capped declarative rules file, so there's no such limit -
this will keep working regardless of how large the book grows.

Why still an allow-list, not blanket-wide (and why NOT COEP: credentialless
either, which looks like the obvious fix for the usual "blanket isolation
breaks third-party embeds" problem): confirmed live that isolating
linux-languages.html (which embeds a YouTube video, no coding-window
instance) breaks the video under EITHER require-corp OR credentialless -
Cross-Origin-Opener-Policy: same-origin itself disrupts the YouTube
player's window/postMessage relationship with its parent page, independent
of COEP's resource-loading policy entirely. credentialless only solves the
*different* problem of a subresource lacking a Cross-Origin-Resource-Policy
header - it does nothing for this failure mode. So blanket isolation (of
any kind) stays unsafe, and the allow-list - which never isolates
linux-languages.html at all, since it has no coding-window instance - is
still the only thing that's actually correct here, not just a size
workaround.

Why generate this instead of hand-maintaining a list: the set of pages that
embed the coding-window tool changes as the book's content changes. Deriving
it fresh from the actual build output every deploy means this can never
drift out of sync with what's really in the book - same reasoning as the
static-file predecessor.

Cloudflare Pages automatically 308-redirects "/page.html" to the
extension-less "/page" as the canonical URL, so page paths are normalized
(both forms stripped to the same extension-less key) before comparing
against the allow-list, rather than relying on matching one exact string -
see generate-headers.py's docstring for the war story about getting this
wrong silently.

functions/_middleware.js must live at the PROJECT ROOT (sibling of this
script), not inside the built site directory that gets deployed - Cloudflare
Pages Functions are discovered relative to where `wrangler pages deploy` is
invoked, not relative to the deployed directory argument.

Usage: python3 generate-middleware.py <built-site-dir> <output-js-path>
"""
import json
import sys
from pathlib import Path

NEEDLE = "coding-window/index.html"

TEMPLATE = """// Cloudflare Pages Function: applies the COOP/COEP isolation headers the
// coding-window tool's interactive stdin needs (see coding-window/README.md),
// scoped ONLY to pages that actually embed the tool. Auto-generated by
// generate-middleware.py from the actual build output every deploy - do not
// hand-edit, it will drift out of sync with the book's content. See that
// script's docstring for the full reasoning (why a Function instead of a
// static _headers file, and why still an allow-list rather than blanket).

const ISOLATED_PAGES = new Set({pages_json});

function normalize(pathname) {{
  let p = pathname.replace(/^\\/+/, "");
  if (p.endsWith(".html")) p = p.slice(0, -".html".length);
  return p;
}}

export async function onRequest(context) {{
  const response = await context.next();
  const path = normalize(new URL(context.request.url).pathname);
  if (!ISOLATED_PAGES.has(path) && !path.startsWith("coding-window/")) {{
    return response;
  }}
  const isolated = new Response(response.body, response);
  isolated.headers.set("Cross-Origin-Opener-Policy", "same-origin");
  isolated.headers.set("Cross-Origin-Embedder-Policy", "require-corp");
  return isolated;
}}
"""


def main():
    if len(sys.argv) != 3:
        print("Usage: python3 generate-middleware.py <built-site-dir> <output-js-path>", file=sys.stderr)
        sys.exit(1)

    site_dir = Path(sys.argv[1])
    output_path = Path(sys.argv[2])

    pages = []
    for html_file in sorted(site_dir.glob("*.html")):
        if NEEDLE in html_file.read_text(errors="ignore"):
            pages.append(html_file.stem)

    # The classroom deck player (external/class.html) shows those book pages as
    # slides in an iframe. Cross-origin isolation only holds when EVERY frame
    # from the top down carries the headers, so the outermost frame needs them
    # too - even though the player embeds no coding window directly, only pages
    # that do. Without this the nested coding windows silently drop to the
    # non-interactive "type your input first" fallback (confirmed live).
    # No ".html" and no leading slash: that is the shape normalize() produces.
    if (site_dir / "external" / "class.html").is_file():
        pages.append("external/class")

    # ...and every page any deck shows as a slide, whether or not it embeds a
    # coding window. A document sent with COEP: require-corp (which the player
    # now is) may only frame documents that assert COEP themselves; one that
    # doesn't is blocked outright, surfacing as "refused to connect". Slides
    # showing pure-prose pages (integers-hex, integers-negative, ...) failed
    # exactly this way until they were added here.
    for deck_file in sorted((site_dir / "external" / "decks").glob("*.json")):
        try:
            deck = json.loads(deck_file.read_text())
        except (ValueError, OSError):
            continue  # icebreakers.json and friends have no slides; ignore junk
        for slide in deck.get("slides", []):
            page = slide.get("page")
            if page:
                stem = page.split("?", 1)[0]
                if stem.endswith(".html"):
                    stem = stem[: -len(".html")]
                if stem not in pages:
                    pages.append(stem)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(TEMPLATE.format(pages_json=json.dumps(pages, indent=2)))
    print(f"Generated {output_path} with isolation headers for {len(pages)} pages plus coding-window/*.")


if __name__ == "__main__":
    main()
