#!/bin/bash
# Usage: scripts/add-applets.sh <output-dir>
#
# sorters.js and findapplets.py live permanently under assets/js/ and scripts/ (both tracked
# in git) since output/ is git-ignored and gets regenerated by `pretext build`. This copies the
# current versions into <output-dir> and rewrites any ADAMSAPPLET...ENDADAMSAPPLET markers in
# its sort*.html/quicksort*.html files into live applet divs plus the sorters.js <script> include.
# Safe to call on a directory with no matching files (no-op). Shared by AddApplets.sh (local,
# single-target dev loop) and the CI workflows (which call it once per deployed target).
set -e

dir="$1"
if [ -z "$dir" ]; then
    echo "Usage: $0 <output-dir>" >&2
    exit 1
fi

cp assets/js/sorters.js "$dir/sorters.js"
cp scripts/findapplets.py "$dir/findapplets.py"

(
    cd "$dir"
    shopt -s nullglob
    files=(sort*.html quicksort*.html)
    if [ ${#files[@]} -gt 0 ]; then
        python3 findapplets.py "${files[@]}"
    fi
)
